---
work_dir: '.'
paths:
    out_dir: outputs
    mimic-iv-ards:
        mimic_dir: data/mimic-iv
        cache_dir: data/mimic-iv-ards/cache
        conf_manual_path: configs/mimiciv_dataset_ards.yaml
        sepsis_patient_path: data/mimic-iv/sepsis_result/sepsis3.csv
        out_dir: outputs/mimic-iv-ards
    mimic-iv-raw:
        mimic_dir: data/mimic-iv
        cache_dir: data/mimic-iv-raw/cache
        conf_manual_path: configs/mimiciv_dataset_raw.yaml
        out_dir: outputs/mimic-iv-raw
    mimic-iv-vent:
        mimic_dir: data/mimic-iv
        cache_dir: data/mimic-iv-vent/cache
        conf_manual_path: configs/mimiciv_dataset_vent.yaml
        ventilation_path: data/mimic-iv/ventilation_result/ventilation.csv
        out_dir: outputs/mimic-iv-vent
    cv:
        conf_manual_path: configs/cv_dataset.yml
        data_dir: data/cv/单病种数据导出.csv
        cache_dir: data/cv/cache
        out_dir: outputs/cv


analyzer:
    data_container:
        n_fold: 5
        seed: 100
